drop table hurace.SkierEvent
drop table hurace.TimeData
drop table hurace.RaceData
drop table hurace.EventType
drop table hurace.Sensor
drop table hurace.StartList
drop table hurace.Skier
drop table hurace.PossibleDiscipline
drop table hurace.Race
drop table hurace.Location
drop table hurace.Discipline
drop table hurace.RaceState
drop table hurace.Season
drop table hurace.StartState
drop table hurace.Country
drop table hurace.Gender